#ifndef ESTRUCTURA_DE_DATOS_H
#define ESTRUCTURA_DE_DATOS_H

// ------------------------------------------------------------------------------------------
// -- Structs --
// ------------------------------------------------------------------------------------------

typedef enum
{
	MENSAJE,
	OBT_INSTRUCCION,
	RET_INSTRUCCION,
	INT_PROCESO,
	FINALIZAR_PROCESO_CPU,
	ENVIAR_PCB,
	ENVIAR_CONTEXTO_EJECUCION,
	INSTRUCCION_IO_STDIN_READ,
	INSTRUCCION_IO_STDOUT_WRITE,
	INSTRUCCION_IO_GEN_SLEEP,
	INSTRUCCION_IO_FS_CREATE,
	INSTRUCCION_IO_FS_DELETE,
	INSTRUCCION_IO_FS_TRUNCATE,
	INSTRUCCION_IO_FS_READ,
	INSTRUCCION_IO_FS_WRITE,
	EJECUTAR_IO_GEN_SLEEP,
	ERROR_IO,
	HANDSHAKE_IO,
	HANDSHAKE_MEMORIA,
	EJECUTAR_MOVIN,
	EJECUTAR_MOVOUT,
	EJECUTAR_COPYSTRING,
	EJECUTAR_IO_STDIN_READ,
	RTA_MOVIN,
	EJECUTAR_IO_STDOUT_WRITE,
	RET_IO_STDIN_READ,
	RET_IO_STDOUT_WRITE,
	PEDIR_MARCO,
	IO_OCUPADA_SLEEP,
	IO_OCUPADA_READ,
	IO_OCUPADA_WRITE,
	FIN_IO,
	PAQUETE,
	CREAR_PROCESO,
	FINALIZAR_PROCESO_MEMORIA,
	FIN_TERM_PRO,
	FIN_CREA_PRO,
	EJECUTAR_RESIZE,
	EJECUTAR_RESIZE_OUT_OF_MEMORY_ERROR,
	IO_OCUPADA_FS_CREATE,
	IO_OCUPADA_FS_DELETE,
	IO_OCUPADA_FS_TRUNCATE,
	IO_OCUPADA_FS_WRITE,
	IO_OCUPADA_FS_READ,
	EJECUTAR_IO_FS_CREATE,
	EJECUTAR_IO_FS_DELETE,
	EJECUTAR_IO_FS_TRUNCATE,
	EJECUTAR_IO_FS_WRITE,
	EJECUTAR_IO_FS_READ,
} op_code;

typedef struct
{
	int size;
	void *stream;
} t_buffer;

typedef struct
{
	op_code codigo_operacion;
	t_buffer *buffer;
} t_paquete;

#endif